"""Generate shell init scripts for at-cmd.

Each shell gets a minimal shim: an alias/function that calls `at-cmd`,
keybindings for inline mode, and nothing else. All logic lives in Python.
The animated spinner runs inside the Python CLI on stderr.
"""

from at_cmd.config import load_config
from at_cmd.keybindings import get_binding


def generate(shell: str) -> str:
    """Return the init script for the given shell.

    Args:
        shell: One of bash, zsh, fish, powershell.

    Returns:
        Shell source code to eval.
    """
    generators = {
        "bash": _bash,
        "zsh": _zsh,
        "fish": _fish,
        "powershell": _powershell,
    }
    fn = generators.get(shell.lower())
    if fn is None:
        raise ValueError(f"Unsupported shell: {shell!r}. Choose from: {', '.join(generators)}")
    cfg = load_config()
    hotkey = get_binding(cfg.hotkey, shell) or get_binding("alt+g", shell)
    undo = get_binding(cfg.undo_key, shell) or get_binding("ctrl+z", shell)
    return fn(hotkey, undo, cfg.default_mode)


# ── shared fragments ──────────────────────────────────────────────
# Each shell needs two behaviors:
#   _submit: call at-cmd → editable prompt → eval
#   _inline: replace buffer → call at-cmd → replace buffer with result
#
# The Python CLI handles the animated spinner on stderr.
# Shell scripts just call `at-cmd --json` and let stderr through.


def _fish(hotkey_seq: str, undo_seq: str, default_mode: str) -> str:
    submit = """\
function _at_cmd_submit
    set -l request $argv
    set -l result (at-cmd --json --shell fish $request)
    or begin; echo "  at-cmd failed" >&2; return 1; end
    set -l cmd (echo $result | jq -r '.command')
    set -l desc (echo $result | jq -r '.description')
    test -n "$desc" && printf '  \\e[2m# %s\\e[0m\\n' "$desc" >&2
    set -l final_cmd
    if read -c "$cmd" -p 'set_color green; printf "\\u276f "; set_color normal' -l final_cmd
        history append -- "$final_cmd"
        eval $final_cmd
    end
end"""

    inline = """\
function _at_cmd_inline
    set -l buf (commandline -b)
    string match -q '@ *' -- "$buf" || return
    set -g _at_original_buf "$buf"
    commandline -r ""; commandline -f repaint
    set -l result (at-cmd --json --shell fish (string replace -r '^@\\s*' '' -- "$buf"))
    if test $status -ne 0; commandline -r "$buf"; commandline -f repaint; return 1; end
    set -l cmd (echo $result | jq -r '.command')
    set -l desc (echo $result | jq -r '.description')
    commandline -r "$cmd"; commandline -f end-of-line; commandline -f repaint
    test -n "$desc" && printf '\\n  \\e[2m# %s\\e[0m' "$desc" >&2
end"""

    undo = """\
function _at_cmd_undo
    if set -q _at_original_buf
        commandline -r "$_at_original_buf"; commandline -f end-of-line; commandline -f repaint
        set -e _at_original_buf
    end
end"""

    if default_mode == "inline":
        enter_fn = """\
function _at_cmd_enter
    set -l buf (commandline -b)
    if string match -q '@ *' -- "$buf"
        _at_cmd_inline
    else
        commandline -f execute
    end
end"""
        hotkey_fn = """\
function _at_cmd_hotkey_submit
    set -l buf (commandline -b)
    string match -q '@ *' -- "$buf" || return
    set -l request (string replace -r '^@\\s*' '' -- "$buf")
    commandline -r ""; commandline -f repaint
    _at_cmd_submit $request
end"""
        bindings = f"""\
bind \\r _at_cmd_enter
bind -M insert \\r _at_cmd_enter
bind {hotkey_seq} _at_cmd_hotkey_submit
bind -M insert {hotkey_seq} _at_cmd_hotkey_submit
bind {undo_seq} _at_cmd_undo
bind -M insert {undo_seq} _at_cmd_undo"""
    else:
        enter_fn = """\
function @ --description "Translate natural language to shell commands"
    if test (count $argv) -eq 0; echo "Usage: @ <request>" >&2; return 1; end
    _at_cmd_submit $argv
end"""
        hotkey_fn = ""
        bindings = f"""\
bind {hotkey_seq} _at_cmd_inline
bind -M insert {hotkey_seq} _at_cmd_inline
bind {undo_seq} _at_cmd_undo
bind -M insert {undo_seq} _at_cmd_undo"""

    return f"""\
# at-cmd shell integration (fish) — generated by `at-cmd init fish`
# default_mode: {default_mode}
{submit}
{inline}
{undo}
{enter_fn}
{hotkey_fn}
{bindings}
"""


def _bash(hotkey_seq: str, undo_seq: str, default_mode: str) -> str:
    submit = """\
_at_cmd_submit() {
    if [[ $# -eq 0 ]]; then echo "Usage: at <request>" >&2; return 1; fi
    local _out
    _out=$(at-cmd --json --shell bash "$@") || { echo "  at-cmd failed" >&2; return 1; }
    local _cmd _desc
    _cmd=$(echo "$_out" | jq -r '.command')
    _desc=$(echo "$_out" | jq -r '.description')
    [[ -n "$_desc" ]] && printf '  \\e[2m# %s\\e[0m\\n' "$_desc" >&2
    local _final
    read -e -i "$_cmd" -p $'\\033[32m\\u276f \\033[0m' _final
    if [[ -n "$_final" ]]; then
        history -s "$_final"
        eval "$_final"
    fi
}"""

    inline = """\
_at_cmd_inline() {
    local buf="$READLINE_LINE"
    [[ "$buf" != @\\ * ]] && return
    _at_original_buf="$buf"
    READLINE_LINE=""; READLINE_POINT=0
    local _out
    _out=$(at-cmd --json --shell bash "${buf#@ }") || { READLINE_LINE="$buf"; READLINE_POINT=${#READLINE_LINE}; return; }
    READLINE_LINE=$(echo "$_out" | jq -r '.command')
    READLINE_POINT=${#READLINE_LINE}
}"""

    undo = """\
_at_cmd_undo() {
    if [[ -n "$_at_original_buf" ]]; then
        READLINE_LINE="$_at_original_buf"; READLINE_POINT=${#READLINE_LINE}; _at_original_buf=""
    fi
}"""

    at_fn = """\
at() {
    _at_cmd_submit "$@"
}"""

    if default_mode == "inline":
        bindings = f"""\
bind -x '{hotkey_seq}: _at_cmd_submit'
bind -x '{undo_seq}: _at_cmd_undo'"""
    else:
        bindings = f"""\
bind -x '{hotkey_seq}: _at_cmd_inline'
bind -x '{undo_seq}: _at_cmd_undo'"""

    return f"""\
# at-cmd shell integration (bash) — generated by `at-cmd init bash`
# default_mode: {default_mode}
{submit}
{inline}
{undo}
{at_fn}
{bindings}
"""


def _zsh(hotkey_seq: str, undo_seq: str, default_mode: str) -> str:
    submit = """\
_at_cmd_submit() {
    if [[ $# -eq 0 ]]; then echo "Usage: at <request>" >&2; return 1; fi
    local result
    result=$(at-cmd --json --shell zsh "$@") || { echo "  at-cmd failed" >&2; return 1; }
    local cmd desc
    cmd=$(echo "$result" | jq -r '.command')
    desc=$(echo "$result" | jq -r '.description')
    [[ -n "$desc" ]] && printf '  \\e[2m# %s\\e[0m\\n' "$desc" >&2
    print -z "$cmd"
}"""

    inline = """\
_at_cmd_inline() {
    local buf="$BUFFER"
    [[ "$buf" != @\\ * ]] && return
    _at_original_buf="$buf"
    BUFFER=""; CURSOR=0; zle redisplay
    local result
    result=$(at-cmd --json --shell zsh "${buf#@ }") || { BUFFER="$buf"; CURSOR=${#BUFFER}; zle redisplay; return; }
    BUFFER=$(echo "$result" | jq -r '.command')
    CURSOR=${#BUFFER}; zle redisplay
}"""

    undo = """\
_at_cmd_undo() {
    if [[ -n "$_at_original_buf" ]]; then
        BUFFER="$_at_original_buf"; CURSOR=${#BUFFER}; _at_original_buf=""; zle redisplay
    fi
}"""

    if default_mode == "inline":
        enter_fn = """\
_at_cmd_enter() {
    if [[ "$BUFFER" == @\\ * ]]; then
        _at_cmd_inline
    else
        zle accept-line
    fi
}
zle -N _at_cmd_enter
zle -N _at_cmd_inline
zle -N _at_cmd_undo"""
        at_fn = """\
at() {
    _at_cmd_submit "$@"
}"""
        bindings = f"""\
bindkey '\\r' _at_cmd_enter
bindkey {hotkey_seq} _at_cmd_inline
bindkey {undo_seq} _at_cmd_undo"""
    else:
        enter_fn = """\
zle -N _at_cmd_inline
zle -N _at_cmd_undo"""
        at_fn = """\
at() {
    _at_cmd_submit "$@"
}"""
        bindings = f"""\
bindkey {hotkey_seq} _at_cmd_inline
bindkey {undo_seq} _at_cmd_undo"""

    return f"""\
# at-cmd shell integration (zsh) — generated by `at-cmd init zsh`
# default_mode: {default_mode}
{submit}
{inline}
{undo}
{enter_fn}
{at_fn}
{bindings}
"""


def _powershell(hotkey_seq: str, undo_seq: str, default_mode: str) -> str:
    submit = """\
function _at_cmd_submit {
    param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Request)
    if (-not $Request -or $Request.Count -eq 0) { Write-Error "Usage: at <request>"; return }
    $result = at-cmd --json --shell powershell ($Request -join ' ')
    if ($LASTEXITCODE -ne 0) { Write-Error "  at-cmd failed"; return }
    $data = $result | ConvertFrom-Json
    if ($data.description) { Write-Host "  # $($data.description)" -ForegroundColor DarkGray }
    $edited = Read-Host -Prompt "`e[32m`u276f`e[0m $($data.command)"
    if (-not $edited) { $edited = $data.command }
    if ($edited.Trim()) {
        if (Get-Module -Name PSReadLine) { [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory($edited) }
        Invoke-Expression $edited
    }
}
function at {
    param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Request)
    _at_cmd_submit @Request
}"""

    inline_block = """\
    $script:_atOriginalBuf = ''
    Set-PSReadLineKeyHandler -Chord '__INLINE_CHORD__' -ScriptBlock {
        $line = $null; $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        if ($line -notmatch '^@ ') { return }
        $script:_atOriginalBuf = $line
        [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, '')
        $result = at-cmd --json --shell powershell ($line -replace '^@\\s*','')
        if ($LASTEXITCODE -ne 0) {
            [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, 0, $line); return
        }
        $cmd = ($result | ConvertFrom-Json).command
        $cl = $null; $cc = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$cl, [ref]$cc)
        [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $cl.Length, $cmd)
    }
    Set-PSReadLineKeyHandler -Chord '__UNDO_CHORD__' -ScriptBlock {
        if ($script:_atOriginalBuf) {
            $line = $null; $cursor = $null
            [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
            [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $script:_atOriginalBuf)
            $script:_atOriginalBuf = ''
        }
    }"""

    inline_block = inline_block.replace("__INLINE_CHORD__", hotkey_seq)
    inline_block = inline_block.replace("__UNDO_CHORD__", undo_seq)

    return f"""\
# at-cmd shell integration (powershell) — generated by `at-cmd init powershell`
# default_mode: {default_mode}
{submit}
if (Get-Module -Name PSReadLine) {{
{inline_block}
}}
"""
